name: 🚀 Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: pioneering-axe-464317-f1
  REGION: europe-west1
  SERVICE_NAME: rag-multisource-assistant
  REPO_NAME: rag-multisource-assistant
  IMAGE_NAME: rag-multisource-assistant

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA .

    - name: Push image to Artifact Registry
      run: |
        docker push europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image=europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA \
          --region=${{ env.REGION }} \
          --platform=managed \
          --allow-unauthenticated \
          --min-instances=1 \
          --set-env-vars=GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
